[package]
name = "tel-ui-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
tel-ui = { path = "../../crates/tel-ui" }
tel-core = { path = "../../crates/tel-core" }
eframe = "0.27"
egui = "0.27"
egui_plot = "0.27"
poll-promise = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = "0.30"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }
alloy-primitives = "1.0.1"
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "tel-ui"
path = "main.rs" 